/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.ExistencePluralIndefinitePhrase;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Existence Plural Indefinite Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistencePluralIndefinitePhraseImpl extends ExistenceAnyPhraseImpl implements ExistencePluralIndefinitePhrase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistencePluralIndefinitePhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXISTENCE_PLURAL_INDEFINITE_PHRASE;
  }

} //ExistencePluralIndefinitePhraseImpl
