/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.ExistenceIndefiniteRefPhrase;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Existence Indefinite Ref Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistenceIndefiniteRefPhraseImpl extends MinimalEObjectImpl.Container implements ExistenceIndefiniteRefPhrase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistenceIndefiniteRefPhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXISTENCE_INDEFINITE_REF_PHRASE;
  }

} //ExistenceIndefiniteRefPhraseImpl
