/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.ExistenceDefinitePhrase;
import org.xtext.example.mydsl.myDsl.ExistenceDefiniteStmt;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Existence Definite Stmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ExistenceDefiniteStmtImpl#getDefinite <em>Definite</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExistenceDefiniteStmtImpl extends ExistenceStmtImpl implements ExistenceDefiniteStmt
{
  /**
   * The cached value of the '{@link #getDefinite() <em>Definite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinite()
   * @generated
   * @ordered
   */
  protected ExistenceDefinitePhrase definite;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistenceDefiniteStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXISTENCE_DEFINITE_STMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceDefinitePhrase getDefinite()
  {
    return definite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefinite(ExistenceDefinitePhrase newDefinite, NotificationChain msgs)
  {
    ExistenceDefinitePhrase oldDefinite = definite;
    definite = newDefinite;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE, oldDefinite, newDefinite);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefinite(ExistenceDefinitePhrase newDefinite)
  {
    if (newDefinite != definite)
    {
      NotificationChain msgs = null;
      if (definite != null)
        msgs = ((InternalEObject)definite).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE, null, msgs);
      if (newDefinite != null)
        msgs = ((InternalEObject)newDefinite).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE, null, msgs);
      msgs = basicSetDefinite(newDefinite, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE, newDefinite, newDefinite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE:
        return basicSetDefinite(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE:
        return getDefinite();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE:
        setDefinite((ExistenceDefinitePhrase)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE:
        setDefinite((ExistenceDefinitePhrase)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXISTENCE_DEFINITE_STMT__DEFINITE:
        return definite != null;
    }
    return super.eIsSet(featureID);
  }

} //ExistenceDefiniteStmtImpl
