/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.ExistenceSingularIndefinitePhrase;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Existence Singular Indefinite Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistenceSingularIndefinitePhraseImpl extends ExistenceAnyPhraseImpl implements ExistenceSingularIndefinitePhrase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistenceSingularIndefinitePhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXISTENCE_SINGULAR_INDEFINITE_PHRASE;
  }

} //ExistenceSingularIndefinitePhraseImpl
