/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.myDsl.CompositionStmt;
import org.xtext.example.mydsl.myDsl.ExistenceAnyPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceAnyRefListPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceDefinitePhrase;
import org.xtext.example.mydsl.myDsl.ExistenceDefiniteRefListPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceDefiniteRefPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceDefiniteStmt;
import org.xtext.example.mydsl.myDsl.ExistenceIndefiniteRefPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceIndefiniteStmt;
import org.xtext.example.mydsl.myDsl.ExistencePluralIndefinitePhrase;
import org.xtext.example.mydsl.myDsl.ExistencePluralIndefiniteRefListPhrase;
import org.xtext.example.mydsl.myDsl.ExistencePluralIndefiniteRefPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceSingularIndefinitePhrase;
import org.xtext.example.mydsl.myDsl.ExistenceSingularIndefiniteRefListPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceSingularIndefiniteRefPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceSingularRefListPhrase;
import org.xtext.example.mydsl.myDsl.ExistenceStmt;
import org.xtext.example.mydsl.myDsl.InheritanceStmt;
import org.xtext.example.mydsl.myDsl.InstanceBuiltinValueIntegerPhrase;
import org.xtext.example.mydsl.myDsl.InstanceBuiltinValuePhrase;
import org.xtext.example.mydsl.myDsl.InstanceBuiltinValueStringPhrase;
import org.xtext.example.mydsl.myDsl.InstanceDirectRefPhrase;
import org.xtext.example.mydsl.myDsl.InstanceIndirectRefPhrase;
import org.xtext.example.mydsl.myDsl.InstanceRefPhrase;
import org.xtext.example.mydsl.myDsl.Model;
import org.xtext.example.mydsl.myDsl.MyDslFactory;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDeclarationStmt;
import org.xtext.example.mydsl.myDsl.OperationDeclarionHeaderStmt;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallArgumentsPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallInRefsObjectsPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallInRefsPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallInRefsRefPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyStmt;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyStmts;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyUnconditionalPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyUnconditionalStmt;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyVariableDeclarationPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionStmt;
import org.xtext.example.mydsl.myDsl.OperationParameterConnectionBuiltinRefPhrase;
import org.xtext.example.mydsl.myDsl.OperationParameterConnectionPhrase;
import org.xtext.example.mydsl.myDsl.OperationParameterPhrase;
import org.xtext.example.mydsl.myDsl.OperationParameterVariableDeclarationPhrase;
import org.xtext.example.mydsl.myDsl.OperationStmt;
import org.xtext.example.mydsl.myDsl.Stmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyDslPackageImpl extends EPackageImpl implements MyDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceDefiniteStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceDefinitePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceDefiniteRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceDefiniteRefListPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceIndefiniteStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceSingularIndefinitePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existencePluralIndefinitePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceSingularIndefiniteRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existencePluralIndefiniteRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceSingularIndefiniteRefListPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existencePluralIndefiniteRefListPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceSingularRefListPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceAnyRefListPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceIndefiniteRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenceAnyPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositionStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inheritanceStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDeclarationStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDeclarionHeaderStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationParameterPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyStmtsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyUnconditionalStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyUnconditionalPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyFunctionCallPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyFunctionCallArgumentsPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyFunctionCallInRefsRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyFunctionCallInRefsPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyFunctionCallInRefsObjectsPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyVariableDeclarationPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationDefinitionBodyConditionalStmtEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationParameterVariableDeclarationPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationParameterConnectionPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationParameterConnectionBuiltinRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instanceRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instanceDirectRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instanceIndirectRefPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instanceBuiltinValuePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instanceBuiltinValueIntegerPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instanceBuiltinValueStringPhraseEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyDslPackageImpl()
  {
    super(eNS_URI, MyDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MyDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyDslPackage init()
  {
    if (isInited) return (MyDslPackage)EPackage.Registry.INSTANCE.getEPackage(MyDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMyDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MyDslPackageImpl theMyDslPackage = registeredMyDslPackage instanceof MyDslPackageImpl ? (MyDslPackageImpl)registeredMyDslPackage : new MyDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theMyDslPackage.createPackageContents();

    // Initialize created meta-data
    theMyDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyDslPackage.eNS_URI, theMyDslPackage);
    return theMyDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Stmt()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStmt()
  {
    return stmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceStmt()
  {
    return existenceStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceDefiniteStmt()
  {
    return existenceDefiniteStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceDefiniteStmt_Definite()
  {
    return (EReference)existenceDefiniteStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceDefinitePhrase()
  {
    return existenceDefinitePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceDefiniteRefPhrase()
  {
    return existenceDefiniteRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceDefiniteRefPhrase_Ref()
  {
    return (EReference)existenceDefiniteRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceDefiniteRefListPhrase()
  {
    return existenceDefiniteRefListPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceDefiniteRefListPhrase_Elements()
  {
    return (EReference)existenceDefiniteRefListPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceIndefiniteStmt()
  {
    return existenceIndefiniteStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceIndefiniteStmt_Plural()
  {
    return (EReference)existenceIndefiniteStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceIndefiniteStmt_Singular()
  {
    return (EReference)existenceIndefiniteStmtEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceSingularIndefinitePhrase()
  {
    return existenceSingularIndefinitePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistencePluralIndefinitePhrase()
  {
    return existencePluralIndefinitePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceSingularIndefiniteRefPhrase()
  {
    return existenceSingularIndefiniteRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceSingularIndefiniteRefPhrase_Ref()
  {
    return (EReference)existenceSingularIndefiniteRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistencePluralIndefiniteRefPhrase()
  {
    return existencePluralIndefiniteRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistencePluralIndefiniteRefPhrase_Ref()
  {
    return (EReference)existencePluralIndefiniteRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceSingularIndefiniteRefListPhrase()
  {
    return existenceSingularIndefiniteRefListPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistenceSingularIndefiniteRefListPhrase_Elements()
  {
    return (EReference)existenceSingularIndefiniteRefListPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistencePluralIndefiniteRefListPhrase()
  {
    return existencePluralIndefiniteRefListPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExistencePluralIndefiniteRefListPhrase_Elements()
  {
    return (EReference)existencePluralIndefiniteRefListPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceSingularRefListPhrase()
  {
    return existenceSingularRefListPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceAnyRefListPhrase()
  {
    return existenceAnyRefListPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceIndefiniteRefPhrase()
  {
    return existenceIndefiniteRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenceAnyPhrase()
  {
    return existenceAnyPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExistenceAnyPhrase_Name()
  {
    return (EAttribute)existenceAnyPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompositionStmt()
  {
    return compositionStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositionStmt_Parent()
  {
    return (EReference)compositionStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositionStmt_Children()
  {
    return (EReference)compositionStmtEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInheritanceStmt()
  {
    return inheritanceStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInheritanceStmt_Class()
  {
    return (EReference)inheritanceStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInheritanceStmt_Superclass()
  {
    return (EReference)inheritanceStmtEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationStmt()
  {
    return operationStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDeclarationStmt()
  {
    return operationDeclarationStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDeclarionHeaderStmt()
  {
    return operationDeclarionHeaderStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDeclarionHeaderStmt_Parameters()
  {
    return (EReference)operationDeclarionHeaderStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationParameterPhrase()
  {
    return operationParameterPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionStmt()
  {
    return operationDefinitionStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionStmt_Header()
  {
    return (EReference)operationDefinitionStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionStmt_Body()
  {
    return (EReference)operationDefinitionStmtEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyStmts()
  {
    return operationDefinitionBodyStmtsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyStmts_Stmts()
  {
    return (EReference)operationDefinitionBodyStmtsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyStmt()
  {
    return operationDefinitionBodyStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyUnconditionalStmt()
  {
    return operationDefinitionBodyUnconditionalStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyUnconditionalPhrase()
  {
    return operationDefinitionBodyUnconditionalPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyFunctionCallPhrase()
  {
    return operationDefinitionBodyFunctionCallPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyFunctionCallPhrase_Arguments()
  {
    return (EReference)operationDefinitionBodyFunctionCallPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyFunctionCallArgumentsPhrase()
  {
    return operationDefinitionBodyFunctionCallArgumentsPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyFunctionCallInRefsRefPhrase()
  {
    return operationDefinitionBodyFunctionCallInRefsRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyFunctionCallInRefsRefPhrase_Ref()
  {
    return (EReference)operationDefinitionBodyFunctionCallInRefsRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyFunctionCallInRefsPhrase()
  {
    return operationDefinitionBodyFunctionCallInRefsPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperationDefinitionBodyFunctionCallInRefsPhrase_Name()
  {
    return (EAttribute)operationDefinitionBodyFunctionCallInRefsPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyFunctionCallInRefsObjectsPhrase()
  {
    return operationDefinitionBodyFunctionCallInRefsObjectsPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyVariableDeclarationPhrase()
  {
    return operationDefinitionBodyVariableDeclarationPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyVariableDeclarationPhrase_Type()
  {
    return (EReference)operationDefinitionBodyVariableDeclarationPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationDefinitionBodyConditionalStmt()
  {
    return operationDefinitionBodyConditionalStmtEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyConditionalStmt_Condition()
  {
    return (EReference)operationDefinitionBodyConditionalStmtEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyConditionalStmt_ThenBody()
  {
    return (EReference)operationDefinitionBodyConditionalStmtEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationDefinitionBodyConditionalStmt_ElseBody()
  {
    return (EReference)operationDefinitionBodyConditionalStmtEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationParameterVariableDeclarationPhrase()
  {
    return operationParameterVariableDeclarationPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationParameterVariableDeclarationPhrase_Type()
  {
    return (EReference)operationParameterVariableDeclarationPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationParameterConnectionPhrase()
  {
    return operationParameterConnectionPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationParameterConnectionBuiltinRefPhrase()
  {
    return operationParameterConnectionBuiltinRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperationParameterConnectionBuiltinRefPhrase_Name()
  {
    return (EAttribute)operationParameterConnectionBuiltinRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstanceRefPhrase()
  {
    return instanceRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInstanceRefPhrase_F()
  {
    return (EReference)instanceRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInstanceRefPhrase_Class()
  {
    return (EReference)instanceRefPhraseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstanceDirectRefPhrase()
  {
    return instanceDirectRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInstanceDirectRefPhrase_Value()
  {
    return (EReference)instanceDirectRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstanceIndirectRefPhrase()
  {
    return instanceIndirectRefPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInstanceIndirectRefPhrase_Parent()
  {
    return (EReference)instanceIndirectRefPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstanceBuiltinValuePhrase()
  {
    return instanceBuiltinValuePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstanceBuiltinValueIntegerPhrase()
  {
    return instanceBuiltinValueIntegerPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInstanceBuiltinValueIntegerPhrase_V()
  {
    return (EAttribute)instanceBuiltinValueIntegerPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstanceBuiltinValueStringPhrase()
  {
    return instanceBuiltinValueStringPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInstanceBuiltinValueStringPhrase_V()
  {
    return (EAttribute)instanceBuiltinValueStringPhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyDslFactory getMyDslFactory()
  {
    return (MyDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__STMT);

    stmtEClass = createEClass(STMT);

    existenceStmtEClass = createEClass(EXISTENCE_STMT);

    existenceDefiniteStmtEClass = createEClass(EXISTENCE_DEFINITE_STMT);
    createEReference(existenceDefiniteStmtEClass, EXISTENCE_DEFINITE_STMT__DEFINITE);

    existenceDefinitePhraseEClass = createEClass(EXISTENCE_DEFINITE_PHRASE);

    existenceDefiniteRefPhraseEClass = createEClass(EXISTENCE_DEFINITE_REF_PHRASE);
    createEReference(existenceDefiniteRefPhraseEClass, EXISTENCE_DEFINITE_REF_PHRASE__REF);

    existenceDefiniteRefListPhraseEClass = createEClass(EXISTENCE_DEFINITE_REF_LIST_PHRASE);
    createEReference(existenceDefiniteRefListPhraseEClass, EXISTENCE_DEFINITE_REF_LIST_PHRASE__ELEMENTS);

    existenceIndefiniteStmtEClass = createEClass(EXISTENCE_INDEFINITE_STMT);
    createEReference(existenceIndefiniteStmtEClass, EXISTENCE_INDEFINITE_STMT__PLURAL);
    createEReference(existenceIndefiniteStmtEClass, EXISTENCE_INDEFINITE_STMT__SINGULAR);

    existenceSingularIndefinitePhraseEClass = createEClass(EXISTENCE_SINGULAR_INDEFINITE_PHRASE);

    existencePluralIndefinitePhraseEClass = createEClass(EXISTENCE_PLURAL_INDEFINITE_PHRASE);

    existenceSingularIndefiniteRefPhraseEClass = createEClass(EXISTENCE_SINGULAR_INDEFINITE_REF_PHRASE);
    createEReference(existenceSingularIndefiniteRefPhraseEClass, EXISTENCE_SINGULAR_INDEFINITE_REF_PHRASE__REF);

    existencePluralIndefiniteRefPhraseEClass = createEClass(EXISTENCE_PLURAL_INDEFINITE_REF_PHRASE);
    createEReference(existencePluralIndefiniteRefPhraseEClass, EXISTENCE_PLURAL_INDEFINITE_REF_PHRASE__REF);

    existenceSingularIndefiniteRefListPhraseEClass = createEClass(EXISTENCE_SINGULAR_INDEFINITE_REF_LIST_PHRASE);
    createEReference(existenceSingularIndefiniteRefListPhraseEClass, EXISTENCE_SINGULAR_INDEFINITE_REF_LIST_PHRASE__ELEMENTS);

    existencePluralIndefiniteRefListPhraseEClass = createEClass(EXISTENCE_PLURAL_INDEFINITE_REF_LIST_PHRASE);
    createEReference(existencePluralIndefiniteRefListPhraseEClass, EXISTENCE_PLURAL_INDEFINITE_REF_LIST_PHRASE__ELEMENTS);

    existenceSingularRefListPhraseEClass = createEClass(EXISTENCE_SINGULAR_REF_LIST_PHRASE);

    existenceAnyRefListPhraseEClass = createEClass(EXISTENCE_ANY_REF_LIST_PHRASE);

    existenceIndefiniteRefPhraseEClass = createEClass(EXISTENCE_INDEFINITE_REF_PHRASE);

    existenceAnyPhraseEClass = createEClass(EXISTENCE_ANY_PHRASE);
    createEAttribute(existenceAnyPhraseEClass, EXISTENCE_ANY_PHRASE__NAME);

    compositionStmtEClass = createEClass(COMPOSITION_STMT);
    createEReference(compositionStmtEClass, COMPOSITION_STMT__PARENT);
    createEReference(compositionStmtEClass, COMPOSITION_STMT__CHILDREN);

    inheritanceStmtEClass = createEClass(INHERITANCE_STMT);
    createEReference(inheritanceStmtEClass, INHERITANCE_STMT__CLASS);
    createEReference(inheritanceStmtEClass, INHERITANCE_STMT__SUPERCLASS);

    operationStmtEClass = createEClass(OPERATION_STMT);

    operationDeclarationStmtEClass = createEClass(OPERATION_DECLARATION_STMT);

    operationDeclarionHeaderStmtEClass = createEClass(OPERATION_DECLARION_HEADER_STMT);
    createEReference(operationDeclarionHeaderStmtEClass, OPERATION_DECLARION_HEADER_STMT__PARAMETERS);

    operationParameterPhraseEClass = createEClass(OPERATION_PARAMETER_PHRASE);

    operationDefinitionStmtEClass = createEClass(OPERATION_DEFINITION_STMT);
    createEReference(operationDefinitionStmtEClass, OPERATION_DEFINITION_STMT__HEADER);
    createEReference(operationDefinitionStmtEClass, OPERATION_DEFINITION_STMT__BODY);

    operationDefinitionBodyStmtsEClass = createEClass(OPERATION_DEFINITION_BODY_STMTS);
    createEReference(operationDefinitionBodyStmtsEClass, OPERATION_DEFINITION_BODY_STMTS__STMTS);

    operationDefinitionBodyStmtEClass = createEClass(OPERATION_DEFINITION_BODY_STMT);

    operationDefinitionBodyUnconditionalStmtEClass = createEClass(OPERATION_DEFINITION_BODY_UNCONDITIONAL_STMT);

    operationDefinitionBodyUnconditionalPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_UNCONDITIONAL_PHRASE);

    operationDefinitionBodyFunctionCallPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_FUNCTION_CALL_PHRASE);
    createEReference(operationDefinitionBodyFunctionCallPhraseEClass, OPERATION_DEFINITION_BODY_FUNCTION_CALL_PHRASE__ARGUMENTS);

    operationDefinitionBodyFunctionCallArgumentsPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_FUNCTION_CALL_ARGUMENTS_PHRASE);

    operationDefinitionBodyFunctionCallInRefsRefPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_REF_PHRASE);
    createEReference(operationDefinitionBodyFunctionCallInRefsRefPhraseEClass, OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_REF_PHRASE__REF);

    operationDefinitionBodyFunctionCallInRefsPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_PHRASE);
    createEAttribute(operationDefinitionBodyFunctionCallInRefsPhraseEClass, OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_PHRASE__NAME);

    operationDefinitionBodyFunctionCallInRefsObjectsPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_OBJECTS_PHRASE);

    operationDefinitionBodyVariableDeclarationPhraseEClass = createEClass(OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE);
    createEReference(operationDefinitionBodyVariableDeclarationPhraseEClass, OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE);

    operationDefinitionBodyConditionalStmtEClass = createEClass(OPERATION_DEFINITION_BODY_CONDITIONAL_STMT);
    createEReference(operationDefinitionBodyConditionalStmtEClass, OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION);
    createEReference(operationDefinitionBodyConditionalStmtEClass, OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY);
    createEReference(operationDefinitionBodyConditionalStmtEClass, OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY);

    operationParameterVariableDeclarationPhraseEClass = createEClass(OPERATION_PARAMETER_VARIABLE_DECLARATION_PHRASE);
    createEReference(operationParameterVariableDeclarationPhraseEClass, OPERATION_PARAMETER_VARIABLE_DECLARATION_PHRASE__TYPE);

    operationParameterConnectionPhraseEClass = createEClass(OPERATION_PARAMETER_CONNECTION_PHRASE);

    operationParameterConnectionBuiltinRefPhraseEClass = createEClass(OPERATION_PARAMETER_CONNECTION_BUILTIN_REF_PHRASE);
    createEAttribute(operationParameterConnectionBuiltinRefPhraseEClass, OPERATION_PARAMETER_CONNECTION_BUILTIN_REF_PHRASE__NAME);

    instanceRefPhraseEClass = createEClass(INSTANCE_REF_PHRASE);
    createEReference(instanceRefPhraseEClass, INSTANCE_REF_PHRASE__F);
    createEReference(instanceRefPhraseEClass, INSTANCE_REF_PHRASE__CLASS);

    instanceDirectRefPhraseEClass = createEClass(INSTANCE_DIRECT_REF_PHRASE);
    createEReference(instanceDirectRefPhraseEClass, INSTANCE_DIRECT_REF_PHRASE__VALUE);

    instanceIndirectRefPhraseEClass = createEClass(INSTANCE_INDIRECT_REF_PHRASE);
    createEReference(instanceIndirectRefPhraseEClass, INSTANCE_INDIRECT_REF_PHRASE__PARENT);

    instanceBuiltinValuePhraseEClass = createEClass(INSTANCE_BUILTIN_VALUE_PHRASE);

    instanceBuiltinValueIntegerPhraseEClass = createEClass(INSTANCE_BUILTIN_VALUE_INTEGER_PHRASE);
    createEAttribute(instanceBuiltinValueIntegerPhraseEClass, INSTANCE_BUILTIN_VALUE_INTEGER_PHRASE__V);

    instanceBuiltinValueStringPhraseEClass = createEClass(INSTANCE_BUILTIN_VALUE_STRING_PHRASE);
    createEAttribute(instanceBuiltinValueStringPhraseEClass, INSTANCE_BUILTIN_VALUE_STRING_PHRASE__V);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    existenceStmtEClass.getESuperTypes().add(this.getStmt());
    existenceDefiniteStmtEClass.getESuperTypes().add(this.getExistenceStmt());
    existenceDefinitePhraseEClass.getESuperTypes().add(this.getExistenceAnyPhrase());
    existenceDefiniteRefListPhraseEClass.getESuperTypes().add(this.getExistenceSingularRefListPhrase());
    existenceDefiniteRefListPhraseEClass.getESuperTypes().add(this.getExistenceAnyRefListPhrase());
    existenceIndefiniteStmtEClass.getESuperTypes().add(this.getExistenceStmt());
    existenceSingularIndefinitePhraseEClass.getESuperTypes().add(this.getExistenceAnyPhrase());
    existencePluralIndefinitePhraseEClass.getESuperTypes().add(this.getExistenceAnyPhrase());
    existenceSingularIndefiniteRefPhraseEClass.getESuperTypes().add(this.getExistenceIndefiniteRefPhrase());
    existencePluralIndefiniteRefPhraseEClass.getESuperTypes().add(this.getExistenceIndefiniteRefPhrase());
    existenceSingularIndefiniteRefListPhraseEClass.getESuperTypes().add(this.getExistenceSingularRefListPhrase());
    existenceSingularIndefiniteRefListPhraseEClass.getESuperTypes().add(this.getExistenceAnyRefListPhrase());
    existencePluralIndefiniteRefListPhraseEClass.getESuperTypes().add(this.getExistenceAnyRefListPhrase());
    compositionStmtEClass.getESuperTypes().add(this.getStmt());
    inheritanceStmtEClass.getESuperTypes().add(this.getStmt());
    operationStmtEClass.getESuperTypes().add(this.getStmt());
    operationDeclarationStmtEClass.getESuperTypes().add(this.getOperationStmt());
    operationDeclarionHeaderStmtEClass.getESuperTypes().add(this.getOperationDeclarationStmt());
    operationDefinitionStmtEClass.getESuperTypes().add(this.getOperationStmt());
    operationDefinitionBodyUnconditionalStmtEClass.getESuperTypes().add(this.getOperationDefinitionBodyStmt());
    operationDefinitionBodyUnconditionalPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyUnconditionalStmt());
    operationDefinitionBodyFunctionCallPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyUnconditionalPhrase());
    operationDefinitionBodyFunctionCallInRefsRefPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallArgumentsPhrase());
    operationDefinitionBodyFunctionCallInRefsObjectsPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallInRefsPhrase());
    operationDefinitionBodyVariableDeclarationPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyUnconditionalPhrase());
    operationDefinitionBodyVariableDeclarationPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallInRefsObjectsPhrase());
    operationDefinitionBodyConditionalStmtEClass.getESuperTypes().add(this.getOperationDefinitionBodyStmt());
    operationParameterVariableDeclarationPhraseEClass.getESuperTypes().add(this.getOperationParameterPhrase());
    operationParameterVariableDeclarationPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallInRefsObjectsPhrase());
    operationParameterConnectionPhraseEClass.getESuperTypes().add(this.getOperationParameterPhrase());
    operationParameterConnectionPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallInRefsPhrase());
    operationParameterConnectionBuiltinRefPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallArgumentsPhrase());
    instanceRefPhraseEClass.getESuperTypes().add(this.getOperationDefinitionBodyFunctionCallArgumentsPhrase());
    instanceBuiltinValueIntegerPhraseEClass.getESuperTypes().add(this.getInstanceBuiltinValuePhrase());
    instanceBuiltinValueStringPhraseEClass.getESuperTypes().add(this.getInstanceBuiltinValuePhrase());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Stmt(), this.getStmt(), null, "stmt", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stmtEClass, Stmt.class, "Stmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceStmtEClass, ExistenceStmt.class, "ExistenceStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceDefiniteStmtEClass, ExistenceDefiniteStmt.class, "ExistenceDefiniteStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistenceDefiniteStmt_Definite(), this.getExistenceDefinitePhrase(), null, "definite", null, 0, 1, ExistenceDefiniteStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenceDefinitePhraseEClass, ExistenceDefinitePhrase.class, "ExistenceDefinitePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceDefiniteRefPhraseEClass, ExistenceDefiniteRefPhrase.class, "ExistenceDefiniteRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistenceDefiniteRefPhrase_Ref(), this.getExistenceDefinitePhrase(), null, "ref", null, 0, 1, ExistenceDefiniteRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenceDefiniteRefListPhraseEClass, ExistenceDefiniteRefListPhrase.class, "ExistenceDefiniteRefListPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistenceDefiniteRefListPhrase_Elements(), this.getExistenceDefiniteRefPhrase(), null, "elements", null, 0, -1, ExistenceDefiniteRefListPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenceIndefiniteStmtEClass, ExistenceIndefiniteStmt.class, "ExistenceIndefiniteStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistenceIndefiniteStmt_Plural(), this.getExistencePluralIndefinitePhrase(), null, "plural", null, 0, 1, ExistenceIndefiniteStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExistenceIndefiniteStmt_Singular(), this.getExistenceSingularIndefinitePhrase(), null, "singular", null, 0, 1, ExistenceIndefiniteStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenceSingularIndefinitePhraseEClass, ExistenceSingularIndefinitePhrase.class, "ExistenceSingularIndefinitePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existencePluralIndefinitePhraseEClass, ExistencePluralIndefinitePhrase.class, "ExistencePluralIndefinitePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceSingularIndefiniteRefPhraseEClass, ExistenceSingularIndefiniteRefPhrase.class, "ExistenceSingularIndefiniteRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistenceSingularIndefiniteRefPhrase_Ref(), this.getExistenceSingularIndefinitePhrase(), null, "ref", null, 0, 1, ExistenceSingularIndefiniteRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existencePluralIndefiniteRefPhraseEClass, ExistencePluralIndefiniteRefPhrase.class, "ExistencePluralIndefiniteRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistencePluralIndefiniteRefPhrase_Ref(), this.getExistencePluralIndefinitePhrase(), null, "ref", null, 0, 1, ExistencePluralIndefiniteRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenceSingularIndefiniteRefListPhraseEClass, ExistenceSingularIndefiniteRefListPhrase.class, "ExistenceSingularIndefiniteRefListPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistenceSingularIndefiniteRefListPhrase_Elements(), this.getExistenceSingularIndefiniteRefPhrase(), null, "elements", null, 0, -1, ExistenceSingularIndefiniteRefListPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existencePluralIndefiniteRefListPhraseEClass, ExistencePluralIndefiniteRefListPhrase.class, "ExistencePluralIndefiniteRefListPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExistencePluralIndefiniteRefListPhrase_Elements(), this.getExistencePluralIndefiniteRefPhrase(), null, "elements", null, 0, -1, ExistencePluralIndefiniteRefListPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenceSingularRefListPhraseEClass, ExistenceSingularRefListPhrase.class, "ExistenceSingularRefListPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceAnyRefListPhraseEClass, ExistenceAnyRefListPhrase.class, "ExistenceAnyRefListPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceIndefiniteRefPhraseEClass, ExistenceIndefiniteRefPhrase.class, "ExistenceIndefiniteRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(existenceAnyPhraseEClass, ExistenceAnyPhrase.class, "ExistenceAnyPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExistenceAnyPhrase_Name(), ecorePackage.getEString(), "name", null, 0, 1, ExistenceAnyPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositionStmtEClass, CompositionStmt.class, "CompositionStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCompositionStmt_Parent(), this.getExistenceSingularRefListPhrase(), null, "parent", null, 0, 1, CompositionStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompositionStmt_Children(), this.getExistenceAnyRefListPhrase(), null, "children", null, 0, 1, CompositionStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(inheritanceStmtEClass, InheritanceStmt.class, "InheritanceStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInheritanceStmt_Class(), this.getExistenceSingularRefListPhrase(), null, "class", null, 0, 1, InheritanceStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInheritanceStmt_Superclass(), this.getExistenceSingularRefListPhrase(), null, "superclass", null, 0, 1, InheritanceStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationStmtEClass, OperationStmt.class, "OperationStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDeclarationStmtEClass, OperationDeclarationStmt.class, "OperationDeclarationStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDeclarionHeaderStmtEClass, OperationDeclarionHeaderStmt.class, "OperationDeclarionHeaderStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDeclarionHeaderStmt_Parameters(), this.getOperationParameterPhrase(), null, "parameters", null, 0, -1, OperationDeclarionHeaderStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationParameterPhraseEClass, OperationParameterPhrase.class, "OperationParameterPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDefinitionStmtEClass, OperationDefinitionStmt.class, "OperationDefinitionStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDefinitionStmt_Header(), this.getOperationDeclarionHeaderStmt(), null, "header", null, 0, 1, OperationDefinitionStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOperationDefinitionStmt_Body(), this.getOperationDefinitionBodyStmts(), null, "body", null, 0, 1, OperationDefinitionStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationDefinitionBodyStmtsEClass, OperationDefinitionBodyStmts.class, "OperationDefinitionBodyStmts", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDefinitionBodyStmts_Stmts(), this.getOperationDefinitionBodyStmt(), null, "stmts", null, 0, -1, OperationDefinitionBodyStmts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationDefinitionBodyStmtEClass, OperationDefinitionBodyStmt.class, "OperationDefinitionBodyStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDefinitionBodyUnconditionalStmtEClass, OperationDefinitionBodyUnconditionalStmt.class, "OperationDefinitionBodyUnconditionalStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDefinitionBodyUnconditionalPhraseEClass, OperationDefinitionBodyUnconditionalPhrase.class, "OperationDefinitionBodyUnconditionalPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDefinitionBodyFunctionCallPhraseEClass, OperationDefinitionBodyFunctionCallPhrase.class, "OperationDefinitionBodyFunctionCallPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDefinitionBodyFunctionCallPhrase_Arguments(), this.getOperationDefinitionBodyFunctionCallArgumentsPhrase(), null, "arguments", null, 0, -1, OperationDefinitionBodyFunctionCallPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationDefinitionBodyFunctionCallArgumentsPhraseEClass, OperationDefinitionBodyFunctionCallArgumentsPhrase.class, "OperationDefinitionBodyFunctionCallArgumentsPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDefinitionBodyFunctionCallInRefsRefPhraseEClass, OperationDefinitionBodyFunctionCallInRefsRefPhrase.class, "OperationDefinitionBodyFunctionCallInRefsRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDefinitionBodyFunctionCallInRefsRefPhrase_Ref(), this.getOperationDefinitionBodyFunctionCallInRefsPhrase(), null, "ref", null, 0, 1, OperationDefinitionBodyFunctionCallInRefsRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationDefinitionBodyFunctionCallInRefsPhraseEClass, OperationDefinitionBodyFunctionCallInRefsPhrase.class, "OperationDefinitionBodyFunctionCallInRefsPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOperationDefinitionBodyFunctionCallInRefsPhrase_Name(), ecorePackage.getEString(), "name", null, 0, 1, OperationDefinitionBodyFunctionCallInRefsPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationDefinitionBodyFunctionCallInRefsObjectsPhraseEClass, OperationDefinitionBodyFunctionCallInRefsObjectsPhrase.class, "OperationDefinitionBodyFunctionCallInRefsObjectsPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationDefinitionBodyVariableDeclarationPhraseEClass, OperationDefinitionBodyVariableDeclarationPhrase.class, "OperationDefinitionBodyVariableDeclarationPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDefinitionBodyVariableDeclarationPhrase_Type(), this.getExistenceSingularIndefinitePhrase(), null, "type", null, 0, 1, OperationDefinitionBodyVariableDeclarationPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationDefinitionBodyConditionalStmtEClass, OperationDefinitionBodyConditionalStmt.class, "OperationDefinitionBodyConditionalStmt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationDefinitionBodyConditionalStmt_Condition(), this.getOperationDefinitionBodyFunctionCallPhrase(), null, "condition", null, 0, 1, OperationDefinitionBodyConditionalStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOperationDefinitionBodyConditionalStmt_ThenBody(), this.getOperationDefinitionBodyStmts(), null, "thenBody", null, 0, 1, OperationDefinitionBodyConditionalStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOperationDefinitionBodyConditionalStmt_ElseBody(), this.getOperationDefinitionBodyStmts(), null, "elseBody", null, 0, 1, OperationDefinitionBodyConditionalStmt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationParameterVariableDeclarationPhraseEClass, OperationParameterVariableDeclarationPhrase.class, "OperationParameterVariableDeclarationPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOperationParameterVariableDeclarationPhrase_Type(), this.getExistenceIndefiniteRefPhrase(), null, "type", null, 0, 1, OperationParameterVariableDeclarationPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationParameterConnectionPhraseEClass, OperationParameterConnectionPhrase.class, "OperationParameterConnectionPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationParameterConnectionBuiltinRefPhraseEClass, OperationParameterConnectionBuiltinRefPhrase.class, "OperationParameterConnectionBuiltinRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOperationParameterConnectionBuiltinRefPhrase_Name(), ecorePackage.getEString(), "name", null, 0, 1, OperationParameterConnectionBuiltinRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instanceRefPhraseEClass, InstanceRefPhrase.class, "InstanceRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInstanceRefPhrase_F(), ecorePackage.getEObject(), null, "f", null, 0, 1, InstanceRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInstanceRefPhrase_Class(), this.getExistenceAnyPhrase(), null, "class", null, 0, 1, InstanceRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instanceDirectRefPhraseEClass, InstanceDirectRefPhrase.class, "InstanceDirectRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInstanceDirectRefPhrase_Value(), this.getInstanceBuiltinValuePhrase(), null, "value", null, 0, 1, InstanceDirectRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instanceIndirectRefPhraseEClass, InstanceIndirectRefPhrase.class, "InstanceIndirectRefPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInstanceIndirectRefPhrase_Parent(), this.getOperationDefinitionBodyFunctionCallInRefsObjectsPhrase(), null, "parent", null, 0, 1, InstanceIndirectRefPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instanceBuiltinValuePhraseEClass, InstanceBuiltinValuePhrase.class, "InstanceBuiltinValuePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(instanceBuiltinValueIntegerPhraseEClass, InstanceBuiltinValueIntegerPhrase.class, "InstanceBuiltinValueIntegerPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInstanceBuiltinValueIntegerPhrase_V(), ecorePackage.getEInt(), "v", null, 0, 1, InstanceBuiltinValueIntegerPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instanceBuiltinValueStringPhraseEClass, InstanceBuiltinValueStringPhrase.class, "InstanceBuiltinValueStringPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInstanceBuiltinValueStringPhrase_V(), ecorePackage.getEString(), "v", null, 0, 1, InstanceBuiltinValueStringPhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //MyDslPackageImpl
