/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.myDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyDslFactoryImpl extends EFactoryImpl implements MyDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MyDslFactory init()
  {
    try
    {
      MyDslFactory theMyDslFactory = (MyDslFactory)EPackage.Registry.INSTANCE.getEFactory(MyDslPackage.eNS_URI);
      if (theMyDslFactory != null)
      {
        return theMyDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MyDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MyDslPackage.MODEL: return createModel();
      case MyDslPackage.STMT: return createStmt();
      case MyDslPackage.EXISTENCE_STMT: return createExistenceStmt();
      case MyDslPackage.EXISTENCE_DEFINITE_STMT: return createExistenceDefiniteStmt();
      case MyDslPackage.EXISTENCE_DEFINITE_PHRASE: return createExistenceDefinitePhrase();
      case MyDslPackage.EXISTENCE_DEFINITE_REF_PHRASE: return createExistenceDefiniteRefPhrase();
      case MyDslPackage.EXISTENCE_DEFINITE_REF_LIST_PHRASE: return createExistenceDefiniteRefListPhrase();
      case MyDslPackage.EXISTENCE_INDEFINITE_STMT: return createExistenceIndefiniteStmt();
      case MyDslPackage.EXISTENCE_SINGULAR_INDEFINITE_PHRASE: return createExistenceSingularIndefinitePhrase();
      case MyDslPackage.EXISTENCE_PLURAL_INDEFINITE_PHRASE: return createExistencePluralIndefinitePhrase();
      case MyDslPackage.EXISTENCE_SINGULAR_INDEFINITE_REF_PHRASE: return createExistenceSingularIndefiniteRefPhrase();
      case MyDslPackage.EXISTENCE_PLURAL_INDEFINITE_REF_PHRASE: return createExistencePluralIndefiniteRefPhrase();
      case MyDslPackage.EXISTENCE_SINGULAR_INDEFINITE_REF_LIST_PHRASE: return createExistenceSingularIndefiniteRefListPhrase();
      case MyDslPackage.EXISTENCE_PLURAL_INDEFINITE_REF_LIST_PHRASE: return createExistencePluralIndefiniteRefListPhrase();
      case MyDslPackage.EXISTENCE_SINGULAR_REF_LIST_PHRASE: return createExistenceSingularRefListPhrase();
      case MyDslPackage.EXISTENCE_ANY_REF_LIST_PHRASE: return createExistenceAnyRefListPhrase();
      case MyDslPackage.EXISTENCE_INDEFINITE_REF_PHRASE: return createExistenceIndefiniteRefPhrase();
      case MyDslPackage.EXISTENCE_ANY_PHRASE: return createExistenceAnyPhrase();
      case MyDslPackage.COMPOSITION_STMT: return createCompositionStmt();
      case MyDslPackage.INHERITANCE_STMT: return createInheritanceStmt();
      case MyDslPackage.OPERATION_STMT: return createOperationStmt();
      case MyDslPackage.OPERATION_DECLARATION_STMT: return createOperationDeclarationStmt();
      case MyDslPackage.OPERATION_DECLARION_HEADER_STMT: return createOperationDeclarionHeaderStmt();
      case MyDslPackage.OPERATION_PARAMETER_PHRASE: return createOperationParameterPhrase();
      case MyDslPackage.OPERATION_DEFINITION_STMT: return createOperationDefinitionStmt();
      case MyDslPackage.OPERATION_DEFINITION_BODY_STMTS: return createOperationDefinitionBodyStmts();
      case MyDslPackage.OPERATION_DEFINITION_BODY_STMT: return createOperationDefinitionBodyStmt();
      case MyDslPackage.OPERATION_DEFINITION_BODY_UNCONDITIONAL_STMT: return createOperationDefinitionBodyUnconditionalStmt();
      case MyDslPackage.OPERATION_DEFINITION_BODY_UNCONDITIONAL_PHRASE: return createOperationDefinitionBodyUnconditionalPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_PHRASE: return createOperationDefinitionBodyFunctionCallPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_ARGUMENTS_PHRASE: return createOperationDefinitionBodyFunctionCallArgumentsPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_REF_PHRASE: return createOperationDefinitionBodyFunctionCallInRefsRefPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_PHRASE: return createOperationDefinitionBodyFunctionCallInRefsPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_OBJECTS_PHRASE: return createOperationDefinitionBodyFunctionCallInRefsObjectsPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE: return createOperationDefinitionBodyVariableDeclarationPhrase();
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT: return createOperationDefinitionBodyConditionalStmt();
      case MyDslPackage.OPERATION_PARAMETER_VARIABLE_DECLARATION_PHRASE: return createOperationParameterVariableDeclarationPhrase();
      case MyDslPackage.OPERATION_PARAMETER_CONNECTION_PHRASE: return createOperationParameterConnectionPhrase();
      case MyDslPackage.OPERATION_PARAMETER_CONNECTION_BUILTIN_REF_PHRASE: return createOperationParameterConnectionBuiltinRefPhrase();
      case MyDslPackage.INSTANCE_REF_PHRASE: return createInstanceRefPhrase();
      case MyDslPackage.INSTANCE_DIRECT_REF_PHRASE: return createInstanceDirectRefPhrase();
      case MyDslPackage.INSTANCE_INDIRECT_REF_PHRASE: return createInstanceIndirectRefPhrase();
      case MyDslPackage.INSTANCE_BUILTIN_VALUE_PHRASE: return createInstanceBuiltinValuePhrase();
      case MyDslPackage.INSTANCE_BUILTIN_VALUE_INTEGER_PHRASE: return createInstanceBuiltinValueIntegerPhrase();
      case MyDslPackage.INSTANCE_BUILTIN_VALUE_STRING_PHRASE: return createInstanceBuiltinValueStringPhrase();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Stmt createStmt()
  {
    StmtImpl stmt = new StmtImpl();
    return stmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceStmt createExistenceStmt()
  {
    ExistenceStmtImpl existenceStmt = new ExistenceStmtImpl();
    return existenceStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceDefiniteStmt createExistenceDefiniteStmt()
  {
    ExistenceDefiniteStmtImpl existenceDefiniteStmt = new ExistenceDefiniteStmtImpl();
    return existenceDefiniteStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceDefinitePhrase createExistenceDefinitePhrase()
  {
    ExistenceDefinitePhraseImpl existenceDefinitePhrase = new ExistenceDefinitePhraseImpl();
    return existenceDefinitePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceDefiniteRefPhrase createExistenceDefiniteRefPhrase()
  {
    ExistenceDefiniteRefPhraseImpl existenceDefiniteRefPhrase = new ExistenceDefiniteRefPhraseImpl();
    return existenceDefiniteRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceDefiniteRefListPhrase createExistenceDefiniteRefListPhrase()
  {
    ExistenceDefiniteRefListPhraseImpl existenceDefiniteRefListPhrase = new ExistenceDefiniteRefListPhraseImpl();
    return existenceDefiniteRefListPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceIndefiniteStmt createExistenceIndefiniteStmt()
  {
    ExistenceIndefiniteStmtImpl existenceIndefiniteStmt = new ExistenceIndefiniteStmtImpl();
    return existenceIndefiniteStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceSingularIndefinitePhrase createExistenceSingularIndefinitePhrase()
  {
    ExistenceSingularIndefinitePhraseImpl existenceSingularIndefinitePhrase = new ExistenceSingularIndefinitePhraseImpl();
    return existenceSingularIndefinitePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistencePluralIndefinitePhrase createExistencePluralIndefinitePhrase()
  {
    ExistencePluralIndefinitePhraseImpl existencePluralIndefinitePhrase = new ExistencePluralIndefinitePhraseImpl();
    return existencePluralIndefinitePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceSingularIndefiniteRefPhrase createExistenceSingularIndefiniteRefPhrase()
  {
    ExistenceSingularIndefiniteRefPhraseImpl existenceSingularIndefiniteRefPhrase = new ExistenceSingularIndefiniteRefPhraseImpl();
    return existenceSingularIndefiniteRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistencePluralIndefiniteRefPhrase createExistencePluralIndefiniteRefPhrase()
  {
    ExistencePluralIndefiniteRefPhraseImpl existencePluralIndefiniteRefPhrase = new ExistencePluralIndefiniteRefPhraseImpl();
    return existencePluralIndefiniteRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceSingularIndefiniteRefListPhrase createExistenceSingularIndefiniteRefListPhrase()
  {
    ExistenceSingularIndefiniteRefListPhraseImpl existenceSingularIndefiniteRefListPhrase = new ExistenceSingularIndefiniteRefListPhraseImpl();
    return existenceSingularIndefiniteRefListPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistencePluralIndefiniteRefListPhrase createExistencePluralIndefiniteRefListPhrase()
  {
    ExistencePluralIndefiniteRefListPhraseImpl existencePluralIndefiniteRefListPhrase = new ExistencePluralIndefiniteRefListPhraseImpl();
    return existencePluralIndefiniteRefListPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceSingularRefListPhrase createExistenceSingularRefListPhrase()
  {
    ExistenceSingularRefListPhraseImpl existenceSingularRefListPhrase = new ExistenceSingularRefListPhraseImpl();
    return existenceSingularRefListPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceAnyRefListPhrase createExistenceAnyRefListPhrase()
  {
    ExistenceAnyRefListPhraseImpl existenceAnyRefListPhrase = new ExistenceAnyRefListPhraseImpl();
    return existenceAnyRefListPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceIndefiniteRefPhrase createExistenceIndefiniteRefPhrase()
  {
    ExistenceIndefiniteRefPhraseImpl existenceIndefiniteRefPhrase = new ExistenceIndefiniteRefPhraseImpl();
    return existenceIndefiniteRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceAnyPhrase createExistenceAnyPhrase()
  {
    ExistenceAnyPhraseImpl existenceAnyPhrase = new ExistenceAnyPhraseImpl();
    return existenceAnyPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CompositionStmt createCompositionStmt()
  {
    CompositionStmtImpl compositionStmt = new CompositionStmtImpl();
    return compositionStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InheritanceStmt createInheritanceStmt()
  {
    InheritanceStmtImpl inheritanceStmt = new InheritanceStmtImpl();
    return inheritanceStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationStmt createOperationStmt()
  {
    OperationStmtImpl operationStmt = new OperationStmtImpl();
    return operationStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDeclarationStmt createOperationDeclarationStmt()
  {
    OperationDeclarationStmtImpl operationDeclarationStmt = new OperationDeclarationStmtImpl();
    return operationDeclarationStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDeclarionHeaderStmt createOperationDeclarionHeaderStmt()
  {
    OperationDeclarionHeaderStmtImpl operationDeclarionHeaderStmt = new OperationDeclarionHeaderStmtImpl();
    return operationDeclarionHeaderStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationParameterPhrase createOperationParameterPhrase()
  {
    OperationParameterPhraseImpl operationParameterPhrase = new OperationParameterPhraseImpl();
    return operationParameterPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionStmt createOperationDefinitionStmt()
  {
    OperationDefinitionStmtImpl operationDefinitionStmt = new OperationDefinitionStmtImpl();
    return operationDefinitionStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyStmts createOperationDefinitionBodyStmts()
  {
    OperationDefinitionBodyStmtsImpl operationDefinitionBodyStmts = new OperationDefinitionBodyStmtsImpl();
    return operationDefinitionBodyStmts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyStmt createOperationDefinitionBodyStmt()
  {
    OperationDefinitionBodyStmtImpl operationDefinitionBodyStmt = new OperationDefinitionBodyStmtImpl();
    return operationDefinitionBodyStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyUnconditionalStmt createOperationDefinitionBodyUnconditionalStmt()
  {
    OperationDefinitionBodyUnconditionalStmtImpl operationDefinitionBodyUnconditionalStmt = new OperationDefinitionBodyUnconditionalStmtImpl();
    return operationDefinitionBodyUnconditionalStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyUnconditionalPhrase createOperationDefinitionBodyUnconditionalPhrase()
  {
    OperationDefinitionBodyUnconditionalPhraseImpl operationDefinitionBodyUnconditionalPhrase = new OperationDefinitionBodyUnconditionalPhraseImpl();
    return operationDefinitionBodyUnconditionalPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyFunctionCallPhrase createOperationDefinitionBodyFunctionCallPhrase()
  {
    OperationDefinitionBodyFunctionCallPhraseImpl operationDefinitionBodyFunctionCallPhrase = new OperationDefinitionBodyFunctionCallPhraseImpl();
    return operationDefinitionBodyFunctionCallPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyFunctionCallArgumentsPhrase createOperationDefinitionBodyFunctionCallArgumentsPhrase()
  {
    OperationDefinitionBodyFunctionCallArgumentsPhraseImpl operationDefinitionBodyFunctionCallArgumentsPhrase = new OperationDefinitionBodyFunctionCallArgumentsPhraseImpl();
    return operationDefinitionBodyFunctionCallArgumentsPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyFunctionCallInRefsRefPhrase createOperationDefinitionBodyFunctionCallInRefsRefPhrase()
  {
    OperationDefinitionBodyFunctionCallInRefsRefPhraseImpl operationDefinitionBodyFunctionCallInRefsRefPhrase = new OperationDefinitionBodyFunctionCallInRefsRefPhraseImpl();
    return operationDefinitionBodyFunctionCallInRefsRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyFunctionCallInRefsPhrase createOperationDefinitionBodyFunctionCallInRefsPhrase()
  {
    OperationDefinitionBodyFunctionCallInRefsPhraseImpl operationDefinitionBodyFunctionCallInRefsPhrase = new OperationDefinitionBodyFunctionCallInRefsPhraseImpl();
    return operationDefinitionBodyFunctionCallInRefsPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyFunctionCallInRefsObjectsPhrase createOperationDefinitionBodyFunctionCallInRefsObjectsPhrase()
  {
    OperationDefinitionBodyFunctionCallInRefsObjectsPhraseImpl operationDefinitionBodyFunctionCallInRefsObjectsPhrase = new OperationDefinitionBodyFunctionCallInRefsObjectsPhraseImpl();
    return operationDefinitionBodyFunctionCallInRefsObjectsPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyVariableDeclarationPhrase createOperationDefinitionBodyVariableDeclarationPhrase()
  {
    OperationDefinitionBodyVariableDeclarationPhraseImpl operationDefinitionBodyVariableDeclarationPhrase = new OperationDefinitionBodyVariableDeclarationPhraseImpl();
    return operationDefinitionBodyVariableDeclarationPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyConditionalStmt createOperationDefinitionBodyConditionalStmt()
  {
    OperationDefinitionBodyConditionalStmtImpl operationDefinitionBodyConditionalStmt = new OperationDefinitionBodyConditionalStmtImpl();
    return operationDefinitionBodyConditionalStmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationParameterVariableDeclarationPhrase createOperationParameterVariableDeclarationPhrase()
  {
    OperationParameterVariableDeclarationPhraseImpl operationParameterVariableDeclarationPhrase = new OperationParameterVariableDeclarationPhraseImpl();
    return operationParameterVariableDeclarationPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationParameterConnectionPhrase createOperationParameterConnectionPhrase()
  {
    OperationParameterConnectionPhraseImpl operationParameterConnectionPhrase = new OperationParameterConnectionPhraseImpl();
    return operationParameterConnectionPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationParameterConnectionBuiltinRefPhrase createOperationParameterConnectionBuiltinRefPhrase()
  {
    OperationParameterConnectionBuiltinRefPhraseImpl operationParameterConnectionBuiltinRefPhrase = new OperationParameterConnectionBuiltinRefPhraseImpl();
    return operationParameterConnectionBuiltinRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceRefPhrase createInstanceRefPhrase()
  {
    InstanceRefPhraseImpl instanceRefPhrase = new InstanceRefPhraseImpl();
    return instanceRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceDirectRefPhrase createInstanceDirectRefPhrase()
  {
    InstanceDirectRefPhraseImpl instanceDirectRefPhrase = new InstanceDirectRefPhraseImpl();
    return instanceDirectRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceIndirectRefPhrase createInstanceIndirectRefPhrase()
  {
    InstanceIndirectRefPhraseImpl instanceIndirectRefPhrase = new InstanceIndirectRefPhraseImpl();
    return instanceIndirectRefPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceBuiltinValuePhrase createInstanceBuiltinValuePhrase()
  {
    InstanceBuiltinValuePhraseImpl instanceBuiltinValuePhrase = new InstanceBuiltinValuePhraseImpl();
    return instanceBuiltinValuePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceBuiltinValueIntegerPhrase createInstanceBuiltinValueIntegerPhrase()
  {
    InstanceBuiltinValueIntegerPhraseImpl instanceBuiltinValueIntegerPhrase = new InstanceBuiltinValueIntegerPhraseImpl();
    return instanceBuiltinValueIntegerPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InstanceBuiltinValueStringPhrase createInstanceBuiltinValueStringPhrase()
  {
    InstanceBuiltinValueStringPhraseImpl instanceBuiltinValueStringPhrase = new InstanceBuiltinValueStringPhraseImpl();
    return instanceBuiltinValueStringPhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyDslPackage getMyDslPackage()
  {
    return (MyDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MyDslPackage getPackage()
  {
    return MyDslPackage.eINSTANCE;
  }

} //MyDslFactoryImpl
