/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallInRefsObjectsPhrase;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Definition Body Function Call In Refs Objects Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationDefinitionBodyFunctionCallInRefsObjectsPhraseImpl extends OperationDefinitionBodyFunctionCallInRefsPhraseImpl implements OperationDefinitionBodyFunctionCallInRefsObjectsPhrase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDefinitionBodyFunctionCallInRefsObjectsPhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_OBJECTS_PHRASE;
  }

} //OperationDefinitionBodyFunctionCallInRefsObjectsPhraseImpl
