/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDeclarationStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Declaration Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationDeclarationStmtImpl extends OperationStmtImpl implements OperationDeclarationStmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDeclarationStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DECLARATION_STMT;
  }

} //OperationDeclarationStmtImpl
