/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallArgumentsPhrase;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Definition Body Function Call Arguments Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationDefinitionBodyFunctionCallArgumentsPhraseImpl extends MinimalEObjectImpl.Container implements OperationDefinitionBodyFunctionCallArgumentsPhrase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDefinitionBodyFunctionCallArgumentsPhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DEFINITION_BODY_FUNCTION_CALL_ARGUMENTS_PHRASE;
  }

} //OperationDefinitionBodyFunctionCallArgumentsPhraseImpl
