/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyUnconditionalPhrase;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Definition Body Unconditional Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationDefinitionBodyUnconditionalPhraseImpl extends OperationDefinitionBodyUnconditionalStmtImpl implements OperationDefinitionBodyUnconditionalPhrase
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDefinitionBodyUnconditionalPhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DEFINITION_BODY_UNCONDITIONAL_PHRASE;
  }

} //OperationDefinitionBodyUnconditionalPhraseImpl
