/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Definition Body Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OperationDefinitionBodyStmtImpl extends MinimalEObjectImpl.Container implements OperationDefinitionBodyStmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDefinitionBodyStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DEFINITION_BODY_STMT;
  }

} //OperationDefinitionBodyStmtImpl
