/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyStmts;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Definition Body Conditional Stmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.OperationDefinitionBodyConditionalStmtImpl#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.OperationDefinitionBodyConditionalStmtImpl#getThenBody <em>Then Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.OperationDefinitionBodyConditionalStmtImpl#getElseBody <em>Else Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationDefinitionBodyConditionalStmtImpl extends OperationDefinitionBodyStmtImpl implements OperationDefinitionBodyConditionalStmt
{
  /**
   * The cached value of the '{@link #getCondition() <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition()
   * @generated
   * @ordered
   */
  protected OperationDefinitionBodyFunctionCallPhrase condition;

  /**
   * The cached value of the '{@link #getThenBody() <em>Then Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThenBody()
   * @generated
   * @ordered
   */
  protected OperationDefinitionBodyStmts thenBody;

  /**
   * The cached value of the '{@link #getElseBody() <em>Else Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElseBody()
   * @generated
   * @ordered
   */
  protected OperationDefinitionBodyStmts elseBody;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDefinitionBodyConditionalStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyFunctionCallPhrase getCondition()
  {
    return condition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCondition(OperationDefinitionBodyFunctionCallPhrase newCondition, NotificationChain msgs)
  {
    OperationDefinitionBodyFunctionCallPhrase oldCondition = condition;
    condition = newCondition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION, oldCondition, newCondition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCondition(OperationDefinitionBodyFunctionCallPhrase newCondition)
  {
    if (newCondition != condition)
    {
      NotificationChain msgs = null;
      if (condition != null)
        msgs = ((InternalEObject)condition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION, null, msgs);
      if (newCondition != null)
        msgs = ((InternalEObject)newCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION, null, msgs);
      msgs = basicSetCondition(newCondition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION, newCondition, newCondition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyStmts getThenBody()
  {
    return thenBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetThenBody(OperationDefinitionBodyStmts newThenBody, NotificationChain msgs)
  {
    OperationDefinitionBodyStmts oldThenBody = thenBody;
    thenBody = newThenBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY, oldThenBody, newThenBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThenBody(OperationDefinitionBodyStmts newThenBody)
  {
    if (newThenBody != thenBody)
    {
      NotificationChain msgs = null;
      if (thenBody != null)
        msgs = ((InternalEObject)thenBody).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY, null, msgs);
      if (newThenBody != null)
        msgs = ((InternalEObject)newThenBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY, null, msgs);
      msgs = basicSetThenBody(newThenBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY, newThenBody, newThenBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationDefinitionBodyStmts getElseBody()
  {
    return elseBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElseBody(OperationDefinitionBodyStmts newElseBody, NotificationChain msgs)
  {
    OperationDefinitionBodyStmts oldElseBody = elseBody;
    elseBody = newElseBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY, oldElseBody, newElseBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setElseBody(OperationDefinitionBodyStmts newElseBody)
  {
    if (newElseBody != elseBody)
    {
      NotificationChain msgs = null;
      if (elseBody != null)
        msgs = ((InternalEObject)elseBody).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY, null, msgs);
      if (newElseBody != null)
        msgs = ((InternalEObject)newElseBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY, null, msgs);
      msgs = basicSetElseBody(newElseBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY, newElseBody, newElseBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION:
        return basicSetCondition(null, msgs);
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY:
        return basicSetThenBody(null, msgs);
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY:
        return basicSetElseBody(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION:
        return getCondition();
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY:
        return getThenBody();
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY:
        return getElseBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION:
        setCondition((OperationDefinitionBodyFunctionCallPhrase)newValue);
        return;
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY:
        setThenBody((OperationDefinitionBodyStmts)newValue);
        return;
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY:
        setElseBody((OperationDefinitionBodyStmts)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION:
        setCondition((OperationDefinitionBodyFunctionCallPhrase)null);
        return;
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY:
        setThenBody((OperationDefinitionBodyStmts)null);
        return;
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY:
        setElseBody((OperationDefinitionBodyStmts)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__CONDITION:
        return condition != null;
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__THEN_BODY:
        return thenBody != null;
      case MyDslPackage.OPERATION_DEFINITION_BODY_CONDITIONAL_STMT__ELSE_BODY:
        return elseBody != null;
    }
    return super.eIsSet(featureID);
  }

} //OperationDefinitionBodyConditionalStmtImpl
