/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.ExistenceSingularIndefinitePhrase;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallInRefsObjectsPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallInRefsPhrase;
import org.xtext.example.mydsl.myDsl.OperationDefinitionBodyVariableDeclarationPhrase;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Definition Body Variable Declaration Phrase</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.OperationDefinitionBodyVariableDeclarationPhraseImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.OperationDefinitionBodyVariableDeclarationPhraseImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationDefinitionBodyVariableDeclarationPhraseImpl extends OperationDefinitionBodyUnconditionalPhraseImpl implements OperationDefinitionBodyVariableDeclarationPhrase
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ExistenceSingularIndefinitePhrase type;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationDefinitionBodyVariableDeclarationPhraseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExistenceSingularIndefinitePhrase getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (ExistenceSingularIndefinitePhrase)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExistenceSingularIndefinitePhrase basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ExistenceSingularIndefinitePhrase newType)
  {
    ExistenceSingularIndefinitePhrase oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME:
        return getName();
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE:
        if (resolve) return getType();
        return basicGetType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE:
        setType((ExistenceSingularIndefinitePhrase)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE:
        setType((ExistenceSingularIndefinitePhrase)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__TYPE:
        return type != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == OperationDefinitionBodyFunctionCallInRefsPhrase.class)
    {
      switch (derivedFeatureID)
      {
        case MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME: return MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_PHRASE__NAME;
        default: return -1;
      }
    }
    if (baseClass == OperationDefinitionBodyFunctionCallInRefsObjectsPhrase.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == OperationDefinitionBodyFunctionCallInRefsPhrase.class)
    {
      switch (baseFeatureID)
      {
        case MyDslPackage.OPERATION_DEFINITION_BODY_FUNCTION_CALL_IN_REFS_PHRASE__NAME: return MyDslPackage.OPERATION_DEFINITION_BODY_VARIABLE_DECLARATION_PHRASE__NAME;
        default: return -1;
      }
    }
    if (baseClass == OperationDefinitionBodyFunctionCallInRefsObjectsPhrase.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //OperationDefinitionBodyVariableDeclarationPhraseImpl
