/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composition Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CompositionStmt#getParent <em>Parent</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CompositionStmt#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCompositionStmt()
 * @model
 * @generated
 */
public interface CompositionStmt extends Stmt
{
  /**
   * Returns the value of the '<em><b>Parent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' containment reference.
   * @see #setParent(ExistenceSingularRefListPhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCompositionStmt_Parent()
   * @model containment="true"
   * @generated
   */
  ExistenceSingularRefListPhrase getParent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CompositionStmt#getParent <em>Parent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' containment reference.
   * @see #getParent()
   * @generated
   */
  void setParent(ExistenceSingularRefListPhrase value);

  /**
   * Returns the value of the '<em><b>Children</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' containment reference.
   * @see #setChildren(ExistenceAnyRefListPhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCompositionStmt_Children()
   * @model containment="true"
   * @generated
   */
  ExistenceAnyRefListPhrase getChildren();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CompositionStmt#getChildren <em>Children</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Children</em>' containment reference.
   * @see #getChildren()
   * @generated
   */
  void setChildren(ExistenceAnyRefListPhrase value);

} // CompositionStmt
