/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existence Definite Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExistenceDefiniteStmt#getDefinite <em>Definite</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistenceDefiniteStmt()
 * @model
 * @generated
 */
public interface ExistenceDefiniteStmt extends ExistenceStmt
{
  /**
   * Returns the value of the '<em><b>Definite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definite</em>' containment reference.
   * @see #setDefinite(ExistenceDefinitePhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistenceDefiniteStmt_Definite()
   * @model containment="true"
   * @generated
   */
  ExistenceDefinitePhrase getDefinite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExistenceDefiniteStmt#getDefinite <em>Definite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definite</em>' containment reference.
   * @see #getDefinite()
   * @generated
   */
  void setDefinite(ExistenceDefinitePhrase value);

} // ExistenceDefiniteStmt
