/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existence Plural Indefinite Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistencePluralIndefinitePhrase()
 * @model
 * @generated
 */
public interface ExistencePluralIndefinitePhrase extends ExistenceAnyPhrase
{
} // ExistencePluralIndefinitePhrase
