/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existence Singular Indefinite Ref Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExistenceSingularIndefiniteRefPhrase#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistenceSingularIndefiniteRefPhrase()
 * @model
 * @generated
 */
public interface ExistenceSingularIndefiniteRefPhrase extends ExistenceIndefiniteRefPhrase
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(ExistenceSingularIndefinitePhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistenceSingularIndefiniteRefPhrase_Ref()
   * @model
   * @generated
   */
  ExistenceSingularIndefinitePhrase getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExistenceSingularIndefiniteRefPhrase#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(ExistenceSingularIndefinitePhrase value);

} // ExistenceSingularIndefiniteRefPhrase
