/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existence Plural Indefinite Ref List Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExistencePluralIndefiniteRefListPhrase#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistencePluralIndefiniteRefListPhrase()
 * @model
 * @generated
 */
public interface ExistencePluralIndefiniteRefListPhrase extends ExistenceAnyRefListPhrase
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ExistencePluralIndefiniteRefPhrase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistencePluralIndefiniteRefListPhrase_Elements()
   * @model containment="true"
   * @generated
   */
  EList<ExistencePluralIndefiniteRefPhrase> getElements();

} // ExistencePluralIndefiniteRefListPhrase
