/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existence Definite Ref Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExistenceDefiniteRefPhrase#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistenceDefiniteRefPhrase()
 * @model
 * @generated
 */
public interface ExistenceDefiniteRefPhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(ExistenceDefinitePhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExistenceDefiniteRefPhrase_Ref()
   * @model
   * @generated
   */
  ExistenceDefinitePhrase getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExistenceDefiniteRefPhrase#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(ExistenceDefinitePhrase value);

} // ExistenceDefiniteRefPhrase
