/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Indirect Ref Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InstanceIndirectRefPhrase#getParent <em>Parent</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceIndirectRefPhrase()
 * @model
 * @generated
 */
public interface InstanceIndirectRefPhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' reference.
   * @see #setParent(OperationDefinitionBodyFunctionCallInRefsObjectsPhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceIndirectRefPhrase_Parent()
   * @model
   * @generated
   */
  OperationDefinitionBodyFunctionCallInRefsObjectsPhrase getParent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InstanceIndirectRefPhrase#getParent <em>Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' reference.
   * @see #getParent()
   * @generated
   */
  void setParent(OperationDefinitionBodyFunctionCallInRefsObjectsPhrase value);

} // InstanceIndirectRefPhrase
