/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Builtin Value Integer Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InstanceBuiltinValueIntegerPhrase#getV <em>V</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceBuiltinValueIntegerPhrase()
 * @model
 * @generated
 */
public interface InstanceBuiltinValueIntegerPhrase extends InstanceBuiltinValuePhrase
{
  /**
   * Returns the value of the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' attribute.
   * @see #setV(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceBuiltinValueIntegerPhrase_V()
   * @model
   * @generated
   */
  int getV();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InstanceBuiltinValueIntegerPhrase#getV <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' attribute.
   * @see #getV()
   * @generated
   */
  void setV(int value);

} // InstanceBuiltinValueIntegerPhrase
