/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Direct Ref Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InstanceDirectRefPhrase#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceDirectRefPhrase()
 * @model
 * @generated
 */
public interface InstanceDirectRefPhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(InstanceBuiltinValuePhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceDirectRefPhrase_Value()
   * @model containment="true"
   * @generated
   */
  InstanceBuiltinValuePhrase getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InstanceDirectRefPhrase#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(InstanceBuiltinValuePhrase value);

} // InstanceDirectRefPhrase
