/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Ref Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InstanceRefPhrase#getF <em>F</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InstanceRefPhrase#getClass_ <em>Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceRefPhrase()
 * @model
 * @generated
 */
public interface InstanceRefPhrase extends OperationDefinitionBodyFunctionCallArgumentsPhrase
{
  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference.
   * @see #setF(EObject)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceRefPhrase_F()
   * @model containment="true"
   * @generated
   */
  EObject getF();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InstanceRefPhrase#getF <em>F</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F</em>' containment reference.
   * @see #getF()
   * @generated
   */
  void setF(EObject value);

  /**
   * Returns the value of the '<em><b>Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class</em>' reference.
   * @see #setClass(ExistenceAnyPhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInstanceRefPhrase_Class()
   * @model
   * @generated
   */
  ExistenceAnyPhrase getClass_();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InstanceRefPhrase#getClass_ <em>Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class</em>' reference.
   * @see #getClass_()
   * @generated
   */
  void setClass(ExistenceAnyPhrase value);

} // InstanceRefPhrase
