/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Variable Declaration Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyVariableDeclarationPhrase#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyVariableDeclarationPhrase()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyVariableDeclarationPhrase extends OperationDefinitionBodyUnconditionalPhrase, OperationDefinitionBodyFunctionCallInRefsObjectsPhrase
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ExistenceSingularIndefinitePhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyVariableDeclarationPhrase_Type()
   * @model
   * @generated
   */
  ExistenceSingularIndefinitePhrase getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyVariableDeclarationPhrase#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ExistenceSingularIndefinitePhrase value);

} // OperationDefinitionBodyVariableDeclarationPhrase
