/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Parameter Connection Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationParameterConnectionPhrase()
 * @model
 * @generated
 */
public interface OperationParameterConnectionPhrase extends OperationParameterPhrase, OperationDefinitionBodyFunctionCallInRefsPhrase
{
} // OperationParameterConnectionPhrase
