/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Conditional Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt#getThenBody <em>Then Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt#getElseBody <em>Else Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyConditionalStmt()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyConditionalStmt extends OperationDefinitionBodyStmt
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(OperationDefinitionBodyFunctionCallPhrase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyConditionalStmt_Condition()
   * @model containment="true"
   * @generated
   */
  OperationDefinitionBodyFunctionCallPhrase getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(OperationDefinitionBodyFunctionCallPhrase value);

  /**
   * Returns the value of the '<em><b>Then Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Body</em>' containment reference.
   * @see #setThenBody(OperationDefinitionBodyStmts)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyConditionalStmt_ThenBody()
   * @model containment="true"
   * @generated
   */
  OperationDefinitionBodyStmts getThenBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt#getThenBody <em>Then Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Body</em>' containment reference.
   * @see #getThenBody()
   * @generated
   */
  void setThenBody(OperationDefinitionBodyStmts value);

  /**
   * Returns the value of the '<em><b>Else Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Body</em>' containment reference.
   * @see #setElseBody(OperationDefinitionBodyStmts)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyConditionalStmt_ElseBody()
   * @model containment="true"
   * @generated
   */
  OperationDefinitionBodyStmts getElseBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyConditionalStmt#getElseBody <em>Else Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Body</em>' containment reference.
   * @see #getElseBody()
   * @generated
   */
  void setElseBody(OperationDefinitionBodyStmts value);

} // OperationDefinitionBodyConditionalStmt
