/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Stmts</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyStmts#getStmts <em>Stmts</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyStmts()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyStmts extends EObject
{
  /**
   * Returns the value of the '<em><b>Stmts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyStmt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmts</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyStmts_Stmts()
   * @model containment="true"
   * @generated
   */
  EList<OperationDefinitionBodyStmt> getStmts();

} // OperationDefinitionBodyStmts
