/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionStmt#getHeader <em>Header</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionStmt#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionStmt()
 * @model
 * @generated
 */
public interface OperationDefinitionStmt extends OperationStmt
{
  /**
   * Returns the value of the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' containment reference.
   * @see #setHeader(OperationDeclarionHeaderStmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionStmt_Header()
   * @model containment="true"
   * @generated
   */
  OperationDeclarionHeaderStmt getHeader();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OperationDefinitionStmt#getHeader <em>Header</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' containment reference.
   * @see #getHeader()
   * @generated
   */
  void setHeader(OperationDeclarionHeaderStmt value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(OperationDefinitionBodyStmts)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionStmt_Body()
   * @model containment="true"
   * @generated
   */
  OperationDefinitionBodyStmts getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.OperationDefinitionStmt#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(OperationDefinitionBodyStmts value);

} // OperationDefinitionStmt
