/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Function Call Arguments Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyFunctionCallArgumentsPhrase()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyFunctionCallArgumentsPhrase extends EObject
{
} // OperationDefinitionBodyFunctionCallArgumentsPhrase
