/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Function Call In Refs Objects Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyFunctionCallInRefsObjectsPhrase()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyFunctionCallInRefsObjectsPhrase extends OperationDefinitionBodyFunctionCallInRefsPhrase
{
} // OperationDefinitionBodyFunctionCallInRefsObjectsPhrase
