/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Declaration Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDeclarationStmt()
 * @model
 * @generated
 */
public interface OperationDeclarationStmt extends OperationStmt
{
} // OperationDeclarationStmt
