/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Function Call Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallPhrase#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyFunctionCallPhrase()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyFunctionCallPhrase extends OperationDefinitionBodyUnconditionalPhrase
{
  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.OperationDefinitionBodyFunctionCallArgumentsPhrase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyFunctionCallPhrase_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<OperationDefinitionBodyFunctionCallArgumentsPhrase> getArguments();

} // OperationDefinitionBodyFunctionCallPhrase
