/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition Body Unconditional Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperationDefinitionBodyUnconditionalStmt()
 * @model
 * @generated
 */
public interface OperationDefinitionBodyUnconditionalStmt extends OperationDefinitionBodyStmt
{
} // OperationDefinitionBodyUnconditionalStmt
